### ISSUE TITLE
No reader function for tag js

### ISSUE THREAD

**Issue by jiangts** [ejlo/lein-externs#2]
My cljs code has the #js reader tag which does not seem to be supported by lein externs. Does anybody know how to fix this/if it's just an issue of updating cljs?

Thanks

**Comment by ejlo** [comment]
Ok, I added the 'js tag to *data-readers* when parsing the files. Does it solve the problem for you?

**Comment by jiangts** [comment]
Yes, it did. Thank you so much for the quick response!
